# NUM_EPOCHS: 100
# MODEL_MEM: 32GB
# ngen_unit of 4 Romans is ~ 81k. We need 10k min but 20--30k is good 
#SIM_FRACTION: 2  # only need 1/2 the sim size as SNN. # use ~2 in BATCH_INFO
# KCOR_FILE: /project2/rkessler/SURVEYS/ROMAN/ROOT/kcor/H23/kcor_WFIRST_CYCLE8_IMGPRISM_2021v3.fits
# num_epochs:          150  # ???
# num_mjd_bins:        180 # WARNING: changing this results in Traceback ???
# num_wavelength_bins: 32  # WARNING: can this be reduced ???
# output_path:  DUMMY # Change me !
sbatch_template_default:      $SBATCH_TEMPLATES/SBATCH_scone_cpu.TEMPLATE
sbatch_ncore_heatmaps:  32
sbatch_mem:             40     # GB

nevt_select_heatmaps:  8500,8500   # desired nevt for Ia,nonIa

init_env_train:   source activate scone_cpu_tf2.6
init_env_heatmaps: source activate scone_cpu_tf2.6


sn_type_id_to_name:
  10: Ia
  11: II
  12: II
  30: II
  110: Ia
  111: II
  112: II
  130: II
Ia_fraction: 0.5
batch_size: 32
categorical: false
class_balanced: true
heatmaps_donefile: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BR-ROMAN-CLAS-TRAIN/3_CLAS/SCONE_TRAIN_f_unix_permissions_TRAIN/heatmaps/done.txt
heatmaps_logfile: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BR-ROMAN-CLAS-TRAIN/3_CLAS/SCONE_TRAIN_f_unix_permissions_TRAIN/heatmaps/create_heatmaps__model_config.log
heatmaps_path: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BR-ROMAN-CLAS-TRAIN/3_CLAS/SCONE_TRAIN_f_unix_permissions_TRAIN/heatmaps
ids_path: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BR-ROMAN-CLAS-TRAIN/3_CLAS/SCONE_TRAIN_f_unix_permissions_TRAIN/heatmaps/ids.hdf5
init_env: source activate scone_cpu_tf2.6
init_env_heatmaps: source activate scone_cpu_tf2.6
job_base_name: BR-ROMAN-CLAS-TRAIN__SCONE_TRAIN_f_unix_permissions_TRAIN
kcor_file: /project2/rkessler/SURVEYS/ROMAN/ROOT/kcor/H23/kcor_WFIRST_CYCLE8_IMGPRISM_2021v3.fits
# lcdata_paths:
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0004_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0001_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0007_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0008_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0006_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0007_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0008_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0006_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0005_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0003_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0007_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0001_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0002_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0004_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0003_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0006_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0004_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0005_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0005_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0008_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0007_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0001_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0003_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0004_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0002_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0006_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0005_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0003_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0008_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0002_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0001_PHOT.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0002_PHOT.FITS.gz
# metadata_paths:
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0004_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0001_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0007_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0008_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0006_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0007_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0008_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0006_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0005_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0003_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0007_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0001_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0002_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0004_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0003_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0006_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0004_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0005_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0005_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0008_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0007_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0001_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0003_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0004_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0002_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL02-0006_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0005_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_SNIaMODEL00-0003_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0008_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL01-0002_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0001_HEAD.FITS.gz
# - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN/PIP_BR-ROMAN-CLAS-TRAIN_TRAIN_NONIaMODEL03-0002_HEAD.FITS.gz
mode: train
model_sbatch_job_path: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BR-ROMAN-CLAS-TRAIN/3_CLAS/SCONE_TRAIN_f_unix_permissions_TRAIN/job.slurm
num_epochs: 100
num_mjd_bins: 180
num_wavelength_bins: 32
output_path: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BR-ROMAN-CLAS-TRAIN/3_CLAS/SCONE_TRAIN_f_unix_permissions_TRAIN
sbatch_header_path: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BR-ROMAN-CLAS-TRAIN/3_CLAS/SCONE_TRAIN_f_unix_permissions_TRAIN/heatmaps/sbatch_header.sh
sim_fraction: 1
trained_model: null
types:
- II
- Ia
